In [38]:
import numpy as np

In [39]:
kohli_runs=np.array([45,72,33,61,99,54,40,76,92,58])
print(kohli_runs)

[45 72 33 61 99 54 40 76 92 58]


In [40]:
type(kohli_runs)

numpy.ndarray

In [41]:
kohli_runs.shape

(10,)

In [42]:
batters=np.array([[45,72,33,61,76],[76,64,92,97,54],[83,89,43,65,21]])
print(batters)

[[45 72 33 61 76]
 [76 64 92 97 54]
 [83 89 43 65 21]]


In [43]:
batters.shape

(3, 5)

In [44]:
batters.ndim

2

In [45]:
batters.dtype

dtype('int64')

In [46]:
batters.size

15

In [47]:
batters.nbytes

120

In [48]:
kohli_runs[0]

np.int64(45)

In [49]:
kohli_runs[-3:]

array([76, 92, 58])

In [50]:
batters[2][0]

np.int64(83)

In [51]:
runs=np.array([23,17,37,92,65,67])
runs.reshape(2,3)

array([[23, 17, 37],
       [92, 65, 67]])

In [52]:
kohli_runs +10

array([ 55,  82,  43,  71, 109,  64,  50,  86, 102,  68])

In [53]:
kohli_runs*2

array([ 90, 144,  66, 122, 198, 108,  80, 152, 184, 116])

In [54]:
np.sum(kohli_runs)

np.int64(630)

In [55]:
np.average(kohli_runs)

np.float64(63.0)

In [56]:
np.mean(kohli_runs)

np.float64(63.0)

In [58]:
np.min(kohli_runs)
np.max(kohli_runs)

np.int64(99)

In [59]:
np.median(kohli_runs)

np.float64(59.5)

In [60]:
np.std(kohli_runs)

np.float64(20.615528128088304)

In [61]:
kohli=np.array([45,72,33,61,76])
gill=np.array([86,34,78,64,67])
print(np.mean(kohli))
print(np.mean(gill))

57.4
65.8


In [62]:
kohli >50

array([False,  True, False,  True,  True])

In [63]:
kohli[kohli >50]

array([72, 61, 76])

In [64]:
toss_win=np.array([1,0,1,1,1,0,1])
np.sum(toss_win)

np.int64(5)

In [65]:
economy=np.array([5,6,7,1,4,6,8,3])
np.min(economy)

np.int64(1)

In [66]:
scores=np.array([[969,778,878],[785,980,322]])
print(scores)

[[969 778 878]
 [785 980 322]]


In [67]:
np.mean(scores,axis=1)

array([875.        , 695.66666667])

In [68]:
np.mean(scores,axis=0)

array([877., 879., 600.])

In [69]:
kohli_runs=np.array([45,72,33,61,88,54,40,76,92,58])
avg_runs = np.mean(kohli_runs)
print("Average runs: ",avg_runs)
if avg_runs >50:
    print("player is in form")
else:
    print("player is not in form")

Average runs:  61.9
player is in form


In [73]:
print(np.sum(kohli_runs[-7:]))
print(np.mean(kohli_runs[-7:]))
print(np.max(kohli_runs[-7:]))

469
67.0
92


In [79]:
virat=np.array([10,62,76,86,54,86,97,98,57,76])
rohit=np.array([98,65,53,86,32,21,54,76,43,65])
print(np.sum(virat))
print(np.sum(rohit))
if np.sum(virat) > np.sum(rohit):
    print("virat scored more runs")
else:
    print("rohit scored more runs")
print("difference : ",np.mean(virat) - np.mean(rohit))
count=0
for i,j in zip(virat,rohit):
    if i >j:
        count+=1
    i=i+1
    j=j+1
print("count: ",count)


702
593
virat scored more runs
difference :  10.900000000000006
count:  7


In [83]:
team_runs=np.array([[45,60,30],[50,70,40],[20,30,50],[60,40,80],[30,20,40]])
print(np.sum(team_runs,axis=1))
print(np.sum(team_runs,axis=0))
print(np.max(np.sum(team_runs,axis=1)))

[135 160 100 180  90]
[205 220 240]
180


In [85]:
player=np.array([10,62,76,86,54,86,97,98,57,76])
print(np.mean(player))
print(np.std(player))
print(np.var(player))
if np.var(player)<15:
    print("player is consistent")
else:
    print("player is not consistent")

70.2
24.870866490735704
618.5600000000001
player is not consistent


In [87]:
runs=np.array([1,4,0,6,2,1,4,0,1,6,2,1])
print("total runs : ",np.sum(runs))
fours=0
sixs=0
for i in runs:
    if i ==6:
        sixs=sixs+1
    elif i==4:
        fours=fours+1
    i=i+1
print("fours : ",fours)
print("sixs : ",sixs)
print("total boundry runs : ",(fours*4)+(sixs*6))
print(np.size(runs))
print("percentage of runs scored through boundries :",((fours+sixs)/np.size(runs))*100)


total runs :  28
fours :  2
sixs :  2
total boundry runs :  20
12
percentage of runs scored through boundries : 33.33333333333333
